server {
    listen 80;
    root /usr/share/nginx/html;

    location /api/ {
        proxy_pass http://backend:8080;
        proxy_read_timeout 120s;
        client_max_body_size 1m;
    }

    location / {
        try_files $uri /index.html;
    }
}
