create table app_user (
    id          bigint generated by default as identity primary key,
    handle      varchar(40)  not null unique,
    created_at  timestamp    not null
);

create table problem (
    id              bigint generated by default as identity primary key,
    slug            varchar(80)  not null unique,
    title           varchar(200) not null,
    difficulty      varchar(10)  not null,
    tags            varchar(500) not null,
    description     text         not null,
    starter_code    text         not null,
    reference_code  text         not null,
    method_name     varchar(100) not null,
    params_json     text         not null,
    return_type     varchar(100) not null,
    compare_mode    varchar(20)  not null,
    time_limit_ms   integer      not null,
    hints_json      text         not null,
    sort_order      integer      not null,
    content_hash    varchar(64)  not null
);

create table test_case (
    id             bigint generated by default as identity primary key,
    problem_id     bigint  not null references problem (id) on delete cascade,
    ordinal        integer not null,
    args_json      text    not null,
    expected_json  text    not null,
    sample         boolean not null
);
create index idx_test_case_problem on test_case (problem_id, ordinal);

create table submission (
    id               bigint generated by default as identity primary key,
    user_id          bigint      not null references app_user (id),
    problem_id       bigint      not null references problem (id) on delete cascade,
    code             text        not null,
    verdict          varchar(30) not null,
    passed           integer     not null,
    total            integer     not null,
    runtime_ms       double precision,
    memory_bytes     bigint,
    allocated_bytes  bigint,
    runtime_beats    double precision,
    memory_beats     double precision,
    message          text,
    failed_test_json text,
    created_at       timestamp   not null
);
create index idx_submission_problem on submission (problem_id, verdict);
create index idx_submission_user on submission (user_id, created_at);

create table scratchpad (
    id          bigint generated by default as identity primary key,
    user_id     bigint       not null references app_user (id),
    title       varchar(200) not null,
    code        text         not null,
    stdin       text         not null,
    updated_at  timestamp    not null
);
create index idx_scratchpad_user on scratchpad (user_id, updated_at);
